### ISSUE TITLE
AddProduct Function

### ISSUE THREAD

**Issue by SaraMahran** [mohamedHessuin/SwmarketProject#13]
(1) "h" variable is not used.
(2) The function only check if there exists a brand Name for the product without checking to which store this product will be added to.
(3) This line : " Brand br=new Brand(BN, "NONE"); " is not clear enough and I can't understand exactly what it does.

**Comment by Abohessuin** [comment]
2-I don't need to check to which store because it is admin add
3-u can read rest of code and u will understand
