### ISSUE TITLE
addBrandGUI in adminGUI

### ISSUE THREAD

**Issue by SaraMahran** [mohamedHessuin/SwmarketProject#22]
The variables names are misleading and I got lost between them not able to understand what they refer to. Also I can't understand exactly what happens in the implementation of this function.

**Comment by Abohessuin** [comment]
public void addBrandGUI(adminController cr,brandDatabase br) {
		String a,b,c;
		System.out.println("Enter brand details");
		System.out.println("brand name:");
		Scanner scan=new Scanner(System.in);
		a=scan.nextLine();//
		System.out.println("brand category:");
		Scanner scann=new Scanner(System.in);
		b=scann.nextLine();//


		Brand brand=new Brand(a, b);
		cr.Addbrand(br, brand);


		System.out.println("if u want to show your list press 8 or other key to not");
		int x_o;
		Scanner ttt=new Scanner(System.in);
		x_o=ttt.nextInt();
		if(x_o==8) {
			br.printfortest();
		}



	}
what the thing u don't understand it is so easy function and variables under the line I take from user
but I will manage the variables name
