### ISSUE TITLE
userAddToCartAndSearch in userGUI

### ISSUE THREAD

**Issue by SaraMahran** [mohamedHessuin/SwmarketProject#24]
(1)This line "product buyproduct = new product(); " refers to a variable called buy product. I can't understand how this line and it's implementation can handle the buy product function needed in the project.
(2)I can't understand why there's a need to buy store in the first place. Mentioned in this line"	store buystore = new store();".

**Comment by Abohessuin** [comment]
where is the issue?!!! u can read the rest of the code to understand why I use this variable and where is the relation between this variable declaration and buy product function !!!!!
