### ISSUE TITLE
Functions were not implemented in these classes.

### ISSUE THREAD

**Issue by MahmoudAbdelrrahman** [mohamedHessuin/SwmarketProject#6]
https://github.com/mohamedHessuin/SwmarketProject/blob/master/ecom%20sys/src/SystemStatictics/systemOfferStaticties.java
https://github.com/mohamedHessuin/SwmarketProject/blob/master/ecom%20sys/src/SystemStatictics/systemProductStatictics.java
https://github.com/mohamedHessuin/SwmarketProject/blob/master/ecom%20sys/src/SystemStatictics/systemUserStaticties.java

**Comment by Abohessuin** [comment]
already implemented it
