### ISSUE TITLE
Here you did not print the statistics 

### ISSUE THREAD

**Issue by MahmoudAbdelrrahman** [mohamedHessuin/SwmarketProject#7]
https://github.com/mohamedHessuin/SwmarketProject/blob/master/ecom%20sys/src/Datatypes/store.java
public void run() {
		if (checkproductviewrs == true) {
			stc.updateUsersView();
			checkproductviewrs = false;
		}
		if (checkproductbuyers == true) {
			stc.updateBuyproducts();
			checkproductbuyers = false;
		}

	}

**Comment by Abohessuin** [comment]
after finishing all project it will printed to avoid annoying me during testing
