### ISSUE TITLE
Constructor should not have all these parameters, you could have used builder pattern

### ISSUE THREAD

**Issue by MahmoudAbdelrrahman** [mohamedHessuin/SwmarketProject#8]
https://github.com/mohamedHessuin/SwmarketProject/blob/master/ecom%20sys/src/Datatypes/ShippingInformatio.java
public ShippingInformatio(String name, String familyname, String city, String town, String streetnumberOrname,
			String shippinginfoType, String mobilenumber, String notes) {
		super();
		this.name = name;
		this.familyname = familyname;
		this.city = city;
		this.town = town;
		this.streetnumberOrname = streetnumberOrname;
		this.shippinginfoType = shippinginfoType;
		this.mobilenumber = mobilenumber;
		this.notes = notes;
	}

**Comment by Abohessuin** [comment]
pleasew check concept of law of demeter,it does not talk about quantity of parametrs and it is constructor that construct class attribute as u don't have any other solution for that
